<!DOCTYPE html>
<html lang='es'>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <!-- Titulo del sitio -->
        <title>{{ trans('sirgrimorum_cms::admin.layout.title') }}</title>
        <!-- Icono del sitio -->
        <link rel="shortcut icon" href="{{asset('images/ico/favicon.ico')}}">
        <!-- Metas adicionales -->
        <meta name="author" content="{{ trans('sirgrimorum_cms::admin.layout.metadata.author') }}">
        <meta name="title" content="{{ trans('sirgrimorum_cms::admin.layout.metadata.title') }}">
        <meta name="description" content="{{ trans('sirgrimorum_cms::admin.layout.metadata.description') }}">
        <meta name="keywords" content="{{ trans('sirgrimorum_cms::admin.layout.metadata.keywords') }}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="csrf-param" content="_token">
        <?php
        if (!config("sirgrimorum_cms.own_bootstrap") || Route::current()->getName() == "sirgrimorum_cms_home") {
            if (str_contains(config("sirgrimorum_cms.bootstrap_path"), ['http', '://'])) {
                echo '<link href="' . config("sirgrimorum_cms.bootstrap_path") . '" rel="stylesheet" type="text/css">';
            } else {
                echo '<link href="' . asset(config("sirgrimorum_cms.bootstrap_path") . '/css/bootstrap.min.css') . '" rel="stylesheet">';
            }
        }
        ?>
        <style>
            /* Generated by Font Squirrel (http://www.fontsquirrel.com) on February 3, 2015 */

            body{
                position: relative;
            }

            .jumbotron p {
                font-weight:normal;
            }

            /* menu */
            #menu_principal img.foto_profile{
                max-height: 42px;
                width: auto;
                margin-bottom: -15px;
                margin-top: -20px;
            }
            .login_menu, .reset_menu{
                width: 250px;
                padding-left: 20px;
                padding-right: 20px;
                margin-top: 30px;
                margin-left: auto;
                margin-right: auto;
            }
            .login_menu .form-group, .reset_menu .form-group{
                margin: 0px 0px 5px 0px;
            }
            .reset_menu{
                display: none;
            }

            /* same height */
            /* columns of same height styles */
            .container-xs-height {
                display:table;
                padding-left:0px;
                padding-right:0px;
            }
            .row-xs-height {
                display: table;
                width: 100%;
            }
            .col-xs-height {
                display: table-cell;
                float: none !important;
            }

            .gris_oscuro{
                background-color: #222;
                border-color: #080808;
                background-image: -webkit-linear-gradient(top,#3c3c3c 0,#222 100%);
                background-image: -o-linear-gradient(top,#3c3c3c 0,#222 100%);
                background-image: -webkit-gradient(linear,left top,left bottom,from(#3c3c3c),to(#222));
                background-image: linear-gradient(to bottom,#3c3c3c 0,#222 100%);
                filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff3c3c3c', endColorstr='#ff222222', GradientType=0);
                filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
                background-repeat: repeat-x;
            }

            /*cuerpo*/

            #main{
                margin-top:51px;
            }

            footer{
                position:static;
                bottom: 0px;
                width: 100%;
            }
            /* footer */
            .cont_footer{
                padding-top: 20px;
                padding-bottom: 20px;
                /*height: 100px;*/
                text-align: center;
            }
            .cont_footer, .cont_footer a{
                color: #eee;
            }

            /* otros */
            .boton_centrado{
                text-align: center;
            }
            .ui-progressbar {
                position: relative;
            }
            .progress-label {
                position: absolute;
                left: 50%;
                top: 4px;
                font-weight: bold;
                /*text-shadow: 1px 1px 0 #fff;*/
            }

            .profile_pic {
                margin-right: 20px;
                min-width: 200px;
            }
            .profile_pic img{
                max-height: 200px;
            }

            .media-body{
                width: 90%;
            }
            .profile_pic .btn-group-xs{
                margin-top:-20px;
            }

            .profile_pic .btn-group-xs button.btn-default{
                background: none;
                border: 0px;
                text-shadow: none;
                box-shadow: none;
            }

            .form-group .form-control{
                margin-bottom: 18px;
            }

            .form-group .input-group .form-control{
                margin-bottom: 0px;
            }

            .form-group .input-group{
                margin-bottom: 18px;
            }

            .form-group .control-label{
                line-height: 14px;
            }

            div.list-group-item{
                cursor: pointer;
            }
            div.list-group-item:hover, div.list-group-item:focus {
                color: #555;
                text-decoration: none;
                background-color: #f5f5f5;
            }
        </style>
        <!-- Campo definido para incluir estilos especificos en las vistas que lo requieran -->
        @yield("selfcss")
        @section("selfjs")
        <?php
        if (!config("sirgrimorum_cms.own_jquery") || Route::current()->getName() == "sirgrimorum_cms_home") {
            echo '<script src="' . asset(config("sirgrimorum_cms.jquerytables_path") . "/js/jquery.min.js") . '"></script>';
        }
        if (!config("sirgrimorum_cms.own_bootstrap") || Route::current()->getName() == "sirgrimorum_cms_home") {
            if (str_contains(config("sirgrimorum_cms.bootstrap_path"), ['http', '://'])) {
                //echo '<script src="' . config("sirgrimorum_cms.bootstrap_path") . '"></script>';
            } else {
                echo '<script src="' . asset(config("sirgrimorum_cms.bootstrap_path") . '/js/bootstrap.min.js') . '"></script>';
            }
        }
        ?>
        @show
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">{{ trans("sirgrimorum_cms::admin.layout.toggle_navigation") }}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ route("sirgrimorum_cms_home",App::getLocale()) }}">
                        {{ trans("sirgrimorum_cms::admin.layout.title") }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">{{ trans("sirgrimorum_cms::admin.layout.labels.home") }}</a></li>
                        @foreach(config("sirgrimorum_cms.admin_routes") as $modelo => $config)
                        <?php
                        if (Lang::has("sirgrimorum_cms::" . strtolower($modelo) . ".labels.plural")){
                            $plurales = trans("sirgrimorum_cms::" . strtolower($modelo) . ".labels.plural");
                        }else{
                            $plurales = ucfirst($modelo).'s';
                        }
                        ?>
                        <li><a href="{{ route('sirgrimorum_cms_modelos::index',['localecode'=> App::getLocale(),'modelo'=>strtolower($modelo)]) }}">{{ $plurales }}</a></li>
                        @endforeach
                        @yield("menuobj")
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{trans('sirgrimorum_cms::admin.layout.labels.' . App::getLocale()) }}<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                @foreach(config("sirgrimorum_cms.list_locales") as $localeCode)
                                <li>
                                    <a rel="alternate" hreflang="{{$localeCode}}" href="{{route('sirgrimorum_cms_home',$localeCode) }}">
                                        {{{ trans('sirgrimorum_cms::admin.layout.labels.'.$localeCode) }}}
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>        <!-- Contenido de la pagina -->
        <div id="main">
            <div class="container">
                @if (session(config("sirgrimorum_cms.status_messages_key")))
                <div class="container">
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="{{trans('sirgrimorum_cms::admin.layout.labels.close')}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                        {!! session(config("sirgrimorum_cms.status_messages_key")) !!}
                    </div>
                </div>
                @endif
                @if (session(config("sirgrimorum_cms.error_messages_key")))
                <div class="container">
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="{{trans('sirgrimorum_cms::admin.layout.labels.close')}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                        {!! session(config("sirgrimorum_cms.error_messages_key")) !!}
                    </div>
                </div>
                @endif
                @yield("contenido")
            </div>

        </div>
        <footer>
            <div class="seccion gris_oscuro">
                <div class="container cont_footer">
                    @section("piedepagina")
                    {{Route::current()->getName()}}
                    @show
                </div>
            </div>
        </footer>
        @yield("modales")
    </body>
</html>
